# Project information
site_name: MooTrain
site_url: https://mootrain.net
site_author: Justin Munzing
# site_description:

# Repository
repo_url: https://github.com/jayseeem/mootrain-docs
repo_name: MooTrain Docs

# Copyright
copyright: Copyright &copy; 2010 - 2026 MooTrain. All rights reserved.

# Configuration
theme:
  name: material
  # custom_dir: material/overrides
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

# Plugins
plugins:
  # - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
      # minify_js: true
      # minify_css: true
      cache_safe: true
      # js_files:
      # css_files:

# Hooks
# hooks:
  # - material/overrides/hooks/shortcodes.py
  # - material/overrides/hooks/translations.py

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: /
      name: Join us on Discord
    - icon: fontawesome/brands/x-twitter
      link: /
    - icon: fontawesome/brands/github
      link: https://github.com/jayseeem/mootrain-docs

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# not_in_nav: |
#   /tutorials/**/*.md

# Page tree
nav:
  - Home: index.md
  - Target:
    - target/index.md
    - Order Cancel Checker: target/order_cancel_checker.md
  - Sam's Club:
    - samsclub/index.md
    - Save Item To List: samsclub/save_to_list.md
    - Quick ATC: samsclub/quick_atc.md